import json
import logging
import os
from typing import Any, Dict

from dynamo_auth_backend import DynamoSessionAuthBackend

from bright_chatbot.client import OpenAIChatClient
from bright_chatbot.models import MessagePrompt, User
from bright_chatbot.providers.twilio import TwilioProvider
from bright_chatbot.utils.exceptions import ValidationError

from request_parser import parse_event_body

xray_recorder = None
try:
    from aws_xray_sdk.core import patch_all
    from aws_xray_sdk.core import xray_recorder

    patch_all()
except ImportError:
    logging.warn("Optional library aws_xray_sdk not found. Skipping patching.")
    pass


def lambda_handler(event: Dict[str, Any], context) -> Dict[str, Any]:
    """
    Handler that receives a callback from twillio
    containing a message sent by the user and responds
    to it with a response generated by an OpenAI model.
    """
    logger = init_logger()
    if logger.level < 30:
        print(f"Received event:\n{json.dumps(event)}")
    # Parse event body:
    parsed_body = parse_event_body(event)
    # Verify signature:
    try:
        verify_request_auth(parsed_body)
    except ValidationError:
        return {
            "isBase64Encoded": False,
            "statusCode": 401,
            "headers": {
                "Content-Type": "application/json",
            },
            "body": json.dumps(
                {"error": "Unauthorized", "message": "Invalid signature"}
            ),
        }
    # Initiate provider and backend:
    provider = TwilioProvider()
    backend = DynamoSessionAuthBackend()
    # Initiate client
    client = OpenAIChatClient(provider=provider, backend=backend)
    # Create User message prompt:
    message_event = parsed_body["params"]
    user = User(user_id=message_event["From"])
    message_prompt = MessagePrompt(
        body=message_event["Body"],
        from_user=user,
    )
    # Record the User Id with X-ray
    if xray_recorder:
        document = xray_recorder.current_segment()
        document.set_user(user.hashed_user_id)
    client.reply(message_prompt)
    return {
        "isBase64Encoded": False,
        "statusCode": 200,
        "headers": {
            "Content-Type": "application/json",
        },
        "body": {},
    }


def init_logger() -> logging.Logger:
    logging.basicConfig()
    logger = logging.getLogger("bright_chatbot")
    logger.setLevel(os.environ.get("LAMBDA_LOG_LEVEL", "WARNING"))
    return logger


def verify_request_auth(parsed_body: Dict[str, Any]):
    """
    Verifies that the request is actually coming from Twillio
    """
    callback_url = parsed_body["callback_url"]
    params = parsed_body["params"]
    headers = parsed_body["headers"]
    signature = headers["X-Twilio-Signature"]
    TwilioProvider().verify_signature(
        callback_url, params, signature, raise_on_failure=True
    )
