from typing import List, Literal

from bright_chatbot.configs.base import BaseSettings
from bright_chatbot.configs.templates import prompts


class ProjectSettings(BaseSettings):
    """
    Main project settings used throughout the application.
    """

    # === General Settings ===

    @property
    def USE_MULTI_THREADING(self) -> bool:
        """
        If set to true, the application will use multiple threads
        for some operations.
        """
        use_threading = self.get("USE_MULTI_THREADING", "true")
        return use_threading.lower() == "true"

    # === Admin Users Settings ====

    @property
    def ADMIN_USERS(self) -> List[str]:
        """
        List of phone numbers of the admin users of the application.
        These users may have special privileges within the application.

        :return: List[str]
        """
        admin_users = self.get("ADMIN_USERS")
        return admin_users.split(",") if admin_users else []

    @property
    def ADMINS_RATE_LIMITED(self) -> bool:
        """
        If set to True, admins will be rate limited as well.
        """
        rate_limit_admins = self.get("ADMINS_RATE_LIMITED", "false")
        return rate_limit_admins.lower() == "true"

    # === Security Settings ===

    @property
    def SECRET_KEY(self) -> str:
        """
        Secret key used to cryptographically sign sensitive data.

        :return: str
        """
        return self.get("SECRET_KEY", required=True)

    # === OpenAI API Settings ===

    @property
    def OPENAI_API_KEY(self) -> str:
        """
        OpenAI API key used to authenticate with the OpenAI API.

        :return: str
        """
        return self.get("OPENAI_API_KEY", required=True, accept_plain_name=True)

    @property
    def IMAGE_GENERATION_SIZE(self) -> Literal["small", "medium", "large"]:
        """
        Size of the image generated by the OpenAI API.
        Accepted values: "small", "medium", "large"

        :return: str
        """
        return self.get("IMAGE_GENERATION_SIZE", "medium")

    # === Rate Limit Settings ===

    @property
    def MAX_REQUESTS_PER_MINUTE(self) -> int:
        """
        Maximum number of requests allowed per minute.

        Not implemented yet.

        :return: int
        """
        return self.get("MAX_REQUESTS_PER_MINUTE", 10, cast=int)

    @property
    def MAX_REQUESTS_PER_SESSION(self) -> int:
        """
        Maximum number of requests allowed per session.

        :return: int
        """
        return self.get("MAX_REQUESTS_PER_SESSION", 100, cast=int)

    @property
    def MAX_SESSION_DURATION_MINUTES(self) -> int:
        """
        Maximum duration of a session in minutes.

        :return: int
        """
        return self.get("MAX_SESSION_DURATION_MINUTES", 180, cast=int)

    @property
    def MAX_SESSIONS_PER_DAY(self) -> int:
        """
        Maximum number of sessions allowed per user per day.

        :return: int
        """
        return self.get("MAX_SESSIONS_PER_DAY", 10, cast=int)

    @property
    def MAX_ACTIVE_SESSIONS(self) -> int:
        """
        Maximum number of active sessions that can exist across all users.

        :return: int
        """
        return self.get("MAX_ACTIVE_SESSIONS", 100, cast=int)

    @property
    def MAX_IMAGE_REQUESTS_PER_SESSION(self) -> int:
        """
        Maximum number of image requests allowed per session.

        :return: int
        """
        return self.get("MAX_IMAGE_REQUESTS_PER_SESSION", 10, cast=int)

    # === DynamoDB Backend Settings ===

    @property
    def DYNAMODB_TABLES_PREFIX(self) -> str:
        """
        Prefix used for all DynamoDB tables names.
        """
        return self.get("DYNAMODB_TABLES_PREFIX", "")

    # === Twilio Provider Settings ===

    @property
    def TWILIO_PHONE_NUMBER(self) -> str:
        """
        Phone number of the Twilio account used to send messages.
        """
        return self.get("TWILIO_PHONE_NUMBER", accept_plain_name=True)

    @property
    def TWILIO_CALLBACK_URL(self) -> str:
        """
        URL of the Twilio callback endpoint.

        This can be used to verify the signature of a received message.
        """
        return self.get("TWILIO_CALLBACK_URL", accept_plain_name=True)

    # === WhatApp Business Provider Settings ===

    @property
    def WHATSAPP_BUSINESS_PHONE_NUMBER_ID(self) -> str:
        """
        Phone number Id of the WhatsApp Business account used to send messages.
        """
        return self.get("WHATSAPP_BUSINESS_PHONE_NUMBER_ID", accept_plain_name=True)

    @property
    def WHATSAPP_BUSINESS_AUTH_TOKEN(self) -> str:
        """
        Authentication Token of the WhatsApp Business account.
        """
        return self.get("WHATSAPP_BUSINESS_AUTH_TOKEN", accept_plain_name=True)

    @property
    def WHATSAPP_BUSINESS_FROM_PHONE_NUMBER(self) -> str:
        """
        Phone number of the Twilio account used to send messages.
        """
        return self.get("WHATSAPP_BUSINESS_FROM_PHONE_NUMBER", accept_plain_name=True)

    @property
    def USER_REFERRAL_LINK(self) -> str:
        """
        User's referral link
        """
        return self.get("USER_REFERRAL_LINK", "https://brightbot.chat/")

    # === Message Templates ===
    @property
    def CHAT_SYSTEM_ROLE_PROMPT(self) -> str:
        """
        Message template used as the prompt for the chat system role.
        """
        role_prompt = self.get("CHAT_SYSTEM_ROLE_PROMPT")
        if not role_prompt:
            role_prompt = prompts.CHAT_SYSTEM_ROLE_PROMPT
        return role_prompt

    @property
    def SESSION_STATUS_PROMPT(self) -> str:
        """
        Message template used as the prompt for the session status
        when the session starts
        """
        session_status_prompt = self.get("SESSION_STATUS_PROMPT")
        if not session_status_prompt:
            session_status_prompt = prompts.SESSION_STATUS_PROMPT
        return session_status_prompt

    @property
    def EXTRA_CONTENT_SYSTEM_PROMPT(self) -> str:
        """
        Extra message template to add as prompt to the session's system
        content.
        """
        return self.get("EXTRA_CONTENT_SYSTEM_PROMPT")

    @property
    def USER_WELCOME_MESSAGE(self) -> str:
        """
        Message template used as the welcome message for the user
        when it sends their first message to the chatbot.
        """
        user_welcome_message = self.get("USER_WELCOME_MESSAGE")
        if not user_welcome_message:
            user_welcome_message = prompts.USER_WELCOME_MESSAGE
        return user_welcome_message
