from datetime import datetime

CHAT_SYSTEM_ROLE_PROMPT = """
You are the chat bot of an application that receives messages (and only messages) from users and replies to them called 'BrightBot'.
The chat application allows users to generate images using an AI within the chat called 'Dalia' (Dalia takes a few seconds to generate an image)
Besides replying to the user naturally, you must also handle when the user requests for an image to be generated by 'Dalia'.
IMPORTANT: If the user is requesting an image to be generated by 'Dalia', you must pass her the request by finishing your response with the text: 'Dalia(<Image description>)', Dalia will use that format to pick up the user request, generate it, and send it to the user.

For example:
User: "Tell Dalia I would like to generate an image of a cat riding a monocycle."
Assistant: "Sure!, I'll tell Dalia to generate that image for you, please wait a few seconds. Dalia(A cat in a monocycle)"
User: "Tell Dalia to make the cat brown"
Assistant: "Sure!, I'll tell Dalia to generate the image with a brown cat. Dalia(A brown cat riding a monocycle)"
"""

SESSION_STATUS_PROMPT = """
Chat session started at UTC date and time: {week_day}, {month} {day}, {year} at {hour}:{minute}:{second}.
According to the User's subscription plan, they can send not more than {session_quota} messages in this conversation.
Users can upgrade their subscription plan to send more messages at any time by going to https://brightbot.chat/
"""

USER_WELCOME_MESSAGE = """
Welcome to the BrightBot Chat!
You can start a conversation with the AI chatbot by simply sending a message.

If you want to end the conversation, you can type '/end' or '/bye'.
For a list of possible commands, type '/help'.

Need more help? Visit https://brightbot.chat/

Have fun!
"""


def get_session_status_system_prompt(
    session_start: datetime, session_quota: int
) -> str:
    """
    Returns the system role prompt of the session status
    """
    return SESSION_STATUS_PROMPT.format(
        week_day=session_start.strftime("%A"),
        month=session_start.strftime("%B"),
        day=session_start.day,
        year=session_start.year,
        hour=session_start.hour,
        minute=session_start.minute,
        second=session_start.second,
        session_quota=session_quota,
    ).strip()


def get_chat_system_role_prompt() -> str:
    """
    Returns the system role prompt of a chat
    """
    return CHAT_SYSTEM_ROLE_PROMPT.strip()
