name: "Deploy Staging CloudFormation Stack"

on:
  push:
    # branches: ['main']
    branches: ['fix-cd-#865c506ub'] #! TODO: REMOVE THIS LINE AND UNCOMMENT ABOVE
    # paths: #! TODO: UNCOMMENT ALL BELOW
    #   - 'deploy/chatbot/template.yml'
    #   - 'deploy/chatbot/package/**'
    #   - 'bright_chatbot/**'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        role-duration-seconds: 1200

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Configure SAM CLI
      id: configure-sam
      uses: aws-actions/setup-sam@v2

    - name: SAM build
      id: sam-build
      working-directory: deploy/chatbot
      run: sam build --debug

    - name: List build directory
      id: list-build-dir
      working-directory: deploy/chatbot
      run: |
        ls .aws-sam/build
    
    - name: List lambda function directory
      id: list-lambda-dir
      working-directory: deploy/chatbot
      run: |
        ls .aws-sam/build/BackendLambdaFunction
    
    - name: Execute lambda function
      id: execute-lambda
      working-directory: deploy/chatbot/.aws-sam/build/BackendLambdaFunction
      run: |
        python -c "from lambda_handler import lambda_handler; lambda_handler({}, {})"

    - name: Deploy Changeset
      id: sam-deploy
      working-directory: deploy/chatbot
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --stack-name brightbot-dev \
            --parameter-overrides \
            ParameterKey=AppName,ParameterValue=brightbot-dev \
            ParameterKey=AppEnvironment,ParameterValue=Staging \
            ParameterKey=AdminEmail,ParameterValue=${{vars.STG_ADMIN_EMAIL}} \
            ParameterKey=LambdaLogLevel,ParameterValue=DEBUG \
            ParameterKey=WhatsAppBusinessAuthToken,ParameterValue=${{secrets.STG_WHATSAPP_BUSINESS_AUTH_TOKEN}} \
            ParameterKey=WhatsAppBusinessPhoneNumberId,ParameterValue=${{secrets.STG_WHATSAPP_BUSINESS_PHONE_NUMBER_ID}} \
            ParameterKey=WhatsAppBusinessFromPhoneNumber,ParameterValue=${{secrets.STG_WHATSAPP_BUSINESS_FROM_PHONE_NUMBER}} \
            ParameterKey=OpenAIAPIKey,ParameterValue=${{secrets.STG_OPENAI_API_KEY}} \
            ParameterKey=BrightChatBotSecretKey,ParameterValue=${{secrets.STG_BRIGHT_CHATBOT_SECRET_KEY}} \
            ParameterKey=StripeApiKey,ParameterValue=${{secrets.STG_STRIPE_API_KEY}} \
            ParameterKey=SentryDSN,ParameterValue=${{secrets.SENTRY_DSN}}
